from app.models.user import User, UserRole
from app.models.refresh_token import RefreshToken
from app.models.audit_log import AuditLog
from app.models.project import Project, ProjectEnvironment, Product
from app.models.test_suite import TestSuite, SuiteType
from app.models.test_run import TestRun, RunStatus
from app.models.test_result import TestResult, TestStatus
from app.models.defect import Defect, DefectSeverity, DefectStatus
from app.models.ai_runs import (
    AICredentialProfile,
    AISkill,
    AITestRun,
    AIRunEvent,
    AIRunStatus,
    AIEventStatus,
    AIStepType,
    AndroidAppBuild,
)
from app.models.visual_qa import (
    DesignArtifact,
    DesignRule,
    SowPart,
    VisualRun,
    VisualFinding,
    ArtifactType,
    VisualRunStatus,
    FindingEngine,
    FindingSeverity,
)
from app.models.orchestrator import (
    OrchestratorRun,
    OrchestratorStepDecision,
    OrchestratorRunStatus,
    OrchestratorStep,
)
from app.models.sow import (
    SowDocument,
    SowDocumentVersion,
    SowSection,
    SowRequirementsLedger,
    SowGenerationJob,
    SowDocumentSource,
    SowDocumentStatus,
    SowVersionKind,
    SowVersionStatus,
    SowSectionStatus,
    SowJobStage,
    SowJobStatus,
    SowLedgerFactType,
    SowUIElementType,
    SowSourceStatus,
)
from app.models.ai_usage import AIUsageEvent, AIKeyLimit
from app.models.project_intelligence import (
    PiStatus,
    PiScreen,
    PiNavigationEdge,
    PiComponent,
    PiBehaviorNote,
    PiCaptureEvent,
    PiChangeLog,
    PiReviewAction,
    PiFlow,
    PiDriftType,
    PiDriftFlag,
    PiDesignPattern,
    # Phase 5 — always importable as a NAME (either the real ORM class or
    # None), never an ImportError: see project_intelligence.py's
    # defensive `_PGVECTOR_AVAILABLE` guard. A stale environment without
    # the `pgvector` package still boots; app.services.pi_embed checks for
    # None before ever touching this.
    PiEmbedding,
)

__all__ = [
    "User",
    "UserRole",
    "RefreshToken",
    "AuditLog",
    "Project",
    "ProjectEnvironment",
    "Product",
    "TestSuite",
    "SuiteType",
    "TestRun",
    "RunStatus",
    "TestResult",
    "TestStatus",
    "Defect",
    "DefectSeverity",
    "DefectStatus",
    "AICredentialProfile",
    "AITestRun",
    "AIRunEvent",
    "AIRunStatus",
    "AIEventStatus",
    "AIStepType",
    "AndroidAppBuild",
    "DesignArtifact",
    "DesignRule",
    "SowPart",
    "VisualRun",
    "VisualFinding",
    "ArtifactType",
    "VisualRunStatus",
    "FindingEngine",
    "FindingSeverity",
    "OrchestratorRun",
    "OrchestratorStepDecision",
    "OrchestratorRunStatus",
    "OrchestratorStep",
    "SowDocument",
    "SowDocumentVersion",
    "SowSection",
    "SowRequirementsLedger",
    "SowGenerationJob",
    "SowDocumentStatus",
    "SowVersionKind",
    "SowVersionStatus",
    "SowSectionStatus",
    "SowJobStage",
    "SowJobStatus",
    "SowLedgerFactType",
    "SowUIElementType",
    "SowDocumentSource",
    "SowSourceStatus",
    "AIUsageEvent",
    "AIKeyLimit",
    "PiStatus",
    "PiScreen",
    "PiNavigationEdge",
    "PiComponent",
    "PiBehaviorNote",
    "PiCaptureEvent",
    "PiChangeLog",
    "PiReviewAction",
    "PiFlow",
    "PiDriftType",
    "PiDriftFlag",
    "PiDesignPattern",
    "PiEmbedding",
]
